### ISSUE TITLE
Preview pane

### ISSUE THREAD

**Issue by Kwadryz** [omeryanar/FileExplorer#12]
Excelent job, I just love it.

Can I do something in order to get a preview of other files than images? (pdf, libre office files, txt, etc.)

Thanks.

**Comment by omeryanar** [comment]
Thanks.
TXT files are not a problem, they can be previewed easily but PDF and office files require additional libraries. I initially considered adding this feature, but assumed that users would prefer to open the file directly rather than preview it. What do you think? Are there any use cases where previewing a PDF or Word document is more useful than opening it?

**Comment by DuckEater** [comment]
I'm also quite confused by the preview pane not working for some very common file types (it actually struggles even with half of my .txt files)

I use preview pane before copying/moving/renaming a file - to check if it looks like the right one,
or when looking for a file in my downloads folder - where they are sometimes randomly named.

**Comment by omeryanar** [comment]
I implemented a plugin-based preview pane so contributors can develop their own plugins.
Built-in plugins support pdf files and text based files (txt, xml, json and code files like cs, xaml etc) in addition to image files.
Latest release (v2.1) contains these new plugins.
Excel and Word file type support coming soon! :)

**Comment by omeryanar** [comment]
Latest release (v2.2) contains Word and Excel file support.
Therefore, I'm closing this issue.
