### ISSUE TITLE
New tab / New window folder personnalisation

### ISSUE THREAD

**Issue by DuckEater** [omeryanar/FileExplorer#22]
In order to reduce the number of clicks needed to access a often used folder, it would be nice to be able to customize the default location when opening a new window, beyond the two current choices (Quick Access and Computer).

We would still be able to access any other folder of Quick Acess list within the same number of clicks, using the Quick Access section of the Navigation Pane.

**Comment by omeryanar** [comment]
I did not change the two available options (Quick Access and Computer) to be compatible with Windows Explorer.
Instead, I've added taskbar JumpList support in order to reduce the number of clicks needed to access user folders (desktop, documents etc) and pinned folders.
(Included in the latest v2.0 release)

![Jumplist](https://user-images.githubusercontent.com/34584700/221010284-db8dc076-2e79-4284-96e0-c6172bbd8f3a.png)
