### ISSUE TITLE
Let me resize the window narrower than 1099px

### ISSUE THREAD

**Issue by DavidBevi** [omeryanar/FileExplorer#54]
Currently there's a minimum size for FileExplorer windows: 
- 1099px in width 
- 618px in height

I'd like to make **smaller windows**.  _(I'm on Win11 Pro - v10.0.22621)_

![image](https://github.com/omeryanar/FileExplorer/assets/61429850/893fde4a-30a6-42f1-b777-e804dba3c40e)

**Comment by ParasiteDelta** [comment]
Just tried the program today, and yeah, was kinda shocked. The min-width for this appears to be at least partially dynamic, as it's 960px for me on a 1440p panel, but the question is why is there a min-width to begin with? The Explorer shell's file browser has no min-width and intelligently culls each element, so why can't this?

In theory, you could set the left column to shrink by percentage to a point, do the same for the data columns in the right pane, and for the love of god, make it to where ALL of the buttons in the tray can shrink to just their respective icons. That alone costs a min-width of ~100px just because some buttons don't collapse and keep their tags on screen. Also, there's a random blank space at the end of the toolbar that should also be cullable, but isn't.

![image](https://github.com/omeryanar/FileExplorer/assets/19669733/9a572424-6de5-4cfa-8f42-c0dac7922abb)

Now, why is all of this a major problem?

On a 1440p screen, using GWM, I cannot have more than TWO WINDOWS OPEN PER PANEL WITH FILEEXPLORER OPEN! Having any more open actively cuts off the FileExplorer window due to its min-width. To put that into perspective, a *file browser* is apparently required to hold ~40% of your total screen width 'just cuz'?

I want to use this program more, I prefer the visual design and layout of it, but between the seemingly random loading screens (for a *file browser*, no less) and the min-width, this just doesn't offer enough to justify adjusting or switching away from GWM + Rust-based CLI tools + CMD with the Fish prompt.

Sorry to be so negative, but this kinda blew my mind.

**Comment by DavidBevi** [comment]
> [...] for the love of god [...]
Woah, it seems a bit excessive 😅
I also am hindered by this biggish min-size, I feel your frustration, but remember that the Dev is sharing this project for free, and they probably haven't encountered this problem in their use case.

**Comment by omeryanar** [comment]
> Currently there's a minimum size for FileExplorer windows:
> 
> * 1099px in width
> * 618px in height
> 
> I'd like to make **smaller windows**. _(I'm on Win11 Pro - v10.0.22621)_
> 
> ![image](https://private-user-images.githubusercontent.com/61429850/278252849-893fde4a-30a6-42f1-b777-e804dba3c40e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTk2NzEsIm5iZiI6MTcwNjQ1OTM3MSwicGF0aCI6Ii82MTQyOTg1MC8yNzgyNTI4NDktODkzZmRlNGEtMzBhNi00MmYxLWI3NzctZTgwNGRiYTNjNDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE2MjkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZmFmYmI5ZTk2MGY1YjEzMTVhNmZmNDE4MDY5ODQ2MzIxMTVmOTNkZmIxNWIxMWEwOWFiNTFmZDljMDM0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fC2VTuTbLjkBjQkIVRQ0krAsI1OgO6C_mP6y2dURej0)

Minimum size is reduced to 480p in width (version 3.0)
