### ISSUE TITLE
After renaming a file or creating a new folder, FileExplorer should refresh automatically

### ISSUE THREAD

**Issue by notdodgeball** [omeryanar/FileExplorer#74]
After renaming a file or creating a new folder, the changes are not displayed, only after a F5 refresh.

**Comment by omeryanar** [comment]
Normally File Explorer automatically refreshes with any operation on the file system (create, rename, delete). However, there was a bug that prevented the change tracking mechanism from working on network drives, and it was fixed in version 3.3.
https://github.com/omeryanar/FileExplorer/issues/65#issuecomment-2028098171 

If you still encounter this problem on v3.3 or higher, can you give some detail about your environment? For example, is this happening only in network drives? (Note that if your windows is installed in a virtual environment (such as Parallels Desktop on Mac) then change tracking mechanism might not work.)

**Comment by notdodgeball** [comment]
It was indeed fixed.
